development:
  adapter: postgresql
  encoding: unicode
  database: bookery_development
  pool: 5
  username: Cruzito
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: bookery_test
  pool: 5
  username: Cruzito
  password: 
